"use server";
/**
 * Internal-artifact generation (Phase WES-4G). SERVER-ONLY.
 * ---------------------------------------------------------------------------
 * The four-step contract, in order, and the order is the design:
 *
 *   1. READ the authoritative structured records.
 *   2. RESOLVE the source snapshot — refuses when a mandatory field is absent,
 *      so no PDF is ever rendered with a blank where a fact belongs.
 *   3. RENDER + HASH. Deterministic: same snapshot + same renderer version
 *      produces byte-identical output, so the hash is reproducible.
 *   4. STORE, then FINALIZE atomically. The object is written first; the
 *      database row is what makes those bytes an artifact. Until the row
 *      exists the object is an unreferenced blob, which is the survivable
 *      failure. See the migration header for every failure mode.
 */
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { getAdminSupabaseClient } from "@/lib/supabase/admin";
import { assertPermission } from "@/lib/auth/require-permission";
import { isFileVisible } from "@/lib/authz/visibility";
import { writeAudit } from "@/lib/audit/log";
import { AuditActions } from "@/lib/audit/events";
import { buildStoragePath, removeObject, sha256Hex, uploadObject } from "@/lib/documents/storage";
import { isGeneratableArtifact, isOnDemandArtifact } from "./feasibility";
import { artifactGenerationPermission } from "./authority";
import { canonicalizeSnapshot, resolveArtifactSource } from "./source";
import { readArtifactSource } from "./service";
import { RENDERER_VERSION, renderArtifact } from "./render";

export type GenerateResult =
  | { ok: true; documentId: string; version: number }
  | { ok: false; error: string; missing?: { field: string; labelFr: string }[] };

/** The document_type each artifact is filed under. */
const TYPE_CODE: Record<string, string> = {
  DEMANDE_TRANSPORT: "DEMANDE_TRANSPORT",
  TRANSPORT_ORDER: "TRANSPORT_ORDER",
};

/**
 * Generate (or regenerate) an internal artifact for a dossier, ON DEMAND.
 *
 * WHAT MAY COME THROUGH HERE (FIN-TRN-DOC-01). Being generatable is not being
 * requestable. `OFFICIAL_INVOICE` is generatable and is produced — once,
 * immutably — by `ensureOfficialInvoiceArtifact` at issuance, on its own
 * allocate-once path with its own finalizer. It has no mandatory-field rule in
 * `source.ts`, so reaching this function with it used to fall through to
 * `resolveArtifactSource`, which answered « Type non générable »: a true
 * sentence about the wrong question, in front of a document the platform makes
 * reliably. It is now refused explicitly, by name, before anything else.
 *
 * AUTHORIZATION — PER ARTIFACT (DEC-FIN-TRN-01/02, ratified 2026-09-28).
 * WES-4G.9 asserted `transport:manage` for both transport artifacts. The two are
 * different acts and the source contract already said so: a Demande needs no
 * vehicle, an Ordre cannot exist without one. The Account Manager holding
 * `transport:request` now generates the request; the Ordre stays with the
 * Transport function under `transport:manage`. The map is in ./authority; this
 * function only obeys it — and still asserts the permission itself, so the
 * panel's button remains convenience and never authority.
 */
export async function generateArtifact(input: {
  fileId: string;
  artifactCode: string;
}): Promise<GenerateResult> {
  if (!isGeneratableArtifact(input.artifactCode)) {
    return { ok: false, error: "artifact_not_generatable" };
  }
  if (!isOnDemandArtifact(input.artifactCode)) {
    return { ok: false, error: "artifact_not_on_demand" };
  }

  // An on-demand artifact with no ratified authority is generated by NOBODY.
  // Unreachable while the two maps agree (pinned by test); total on purpose, so
  // a future code added to one map and not the other fails closed.
  const permission = artifactGenerationPermission(input.artifactCode);
  if (!permission) {
    return { ok: false, error: "artifact_not_on_demand" };
  }

  let user;
  try {
    user = await assertPermission(permission);
  } catch {
    return { ok: false, error: "forbidden" };
  }
  if (!(await isFileVisible(user.id, user.tenantId, input.fileId))) {
    return { ok: false, error: "forbidden" };
  }

  const supabase = getAdminSupabaseClient();

  // ---- 1. the authoritative records ---------------------------------------
  // Shared with the panel (`readArtifactSource`): the completeness state the
  // operator sees and the refusal the generator applies come from ONE read.
  // Two implementations would drift, and the drift would look like a Générer
  // button that fails when pressed.
  const source = await readArtifactSource(supabase, user.tenantId, input.fileId);
  if (!source) return { ok: false, error: "not_found" };

  const { data: org } = await supabase
    .from("organization").select("name").eq("id", user.tenantId)
    .maybeSingle<{ name: string }>();

  // ---- 2. refuse rather than render blanks --------------------------------
  const resolved = resolveArtifactSource(input.artifactCode, source);
  if (!resolved.ok) {
    return { ok: false, error: "incomplete_source", missing: resolved.missing };
  }

  // ---- 3. render + hash ---------------------------------------------------
  const { data: current } = await supabase
    .from("document")
    .select("version")
    .eq("tenant_id", user.tenantId)
    .eq("file_id", input.fileId)
    .eq("artifact_code", input.artifactCode)
    .is("superseded_by_id", null)
    .is("deleted_at", null)
    .order("version", { ascending: false })
    .limit(1)
    .maybeSingle<{ version: number }>();
  const nextVersion = (current?.version ?? 0) + 1;

  // RQ / Alternative B — MINTED ONCE, here, and used twice: printed on the PDF
  // and persisted verbatim as `document.generated_at`. Reading the clock twice
  // (once to render, once at INSERT) is precisely the bug this avoids — two
  // reads moments apart can straddle midnight and put one date on the paper and
  // another on the row. `now()` in the RPC remains only the fallback for callers
  // that supply nothing; it is never a second source of truth for this path.
  const generatedAt = new Date().toISOString();

  let bytes: Uint8Array;
  try {
    bytes = renderArtifact({
      artifactCode: input.artifactCode,
      snapshot: resolved.snapshot,
      provenance: resolved.provenance,
      organizationName: org?.name ?? "",
      artifactVersion: nextVersion,
      generatedAt,
    });
  } catch {
    return { ok: false, error: "render_failed" };
  }

  const contentSha256 = sha256Hex(bytes);
  const sourceSha256 = sha256Hex(
    new TextEncoder().encode(canonicalizeSnapshot(resolved.snapshot)),
  );

  // ---- 4. store, then finalize atomically ---------------------------------
  const documentId = randomUUID();
  const path = buildStoragePath(user.tenantId, input.fileId, documentId, "pdf");

  const up = await uploadObject(path, bytes, "application/pdf");
  if (!up.ok) return { ok: false, error: "storage_failed" };

  const { data, error } = await supabase.rpc("finalize_generated_artifact", {
    p_document_id: documentId,
    p_tenant_id: user.tenantId,
    p_file_id: input.fileId,
    p_artifact_code: input.artifactCode,
    p_type_code: TYPE_CODE[input.artifactCode],
    p_storage_path: path,
    p_content_sha256: contentSha256,
    p_source_sha256: sourceSha256,
    p_source_snapshot: resolved.snapshot,
    p_renderer_version: RENDERER_VERSION,
    p_provenance: resolved.provenance,
    p_actor: user.id,
    p_size_bytes: bytes.byteLength,
    p_policy_id: null,
    // The SAME value that was rendered onto the page. Migration 120 honours it
    // via coalesce(p_generated_at, now()).
    p_generated_at: generatedAt,
  });

  if (error) {
    // The object exists and nothing references it. Remove it best-effort; if
    // this also fails it stays as an unreferenced blob, which is harmless —
    // no row, no event, no artifact.
    await removeObject(path);
    return { ok: false, error: "finalize_failed" };
  }

  const result = data as { version: number } | null;

  await writeAudit({
    action: AuditActions.DOCUMENT_UPLOADED,
    actorId: user.id,
    tenantId: user.tenantId,
    entity: "document",
    entityId: documentId,
    after: {
      artifact_code: input.artifactCode,
      version: result?.version ?? nextVersion,
      renderer_version: RENDERER_VERSION,
      content_sha256: contentSha256,
    },
  });

  revalidatePath(`/files/${input.fileId}`);
  return { ok: true, documentId, version: result?.version ?? nextVersion };
}
