/**
 * Per-artifact generation authority (FIN-TRN-DOC-01). PURE — client + server safe.
 * ---------------------------------------------------------------------------
 * WHO may ask the platform to produce a given artifact. One map, read by the
 * server action that decides and by the page that renders the button, so the
 * two can never drift into offering a control the action refuses.
 *
 * RATIFIED 2026-09-28 (DEC-FIN-TRN-01, DEC-FIN-TRN-02), closing the question
 * MAYA-P1.10 §6 left open.
 *
 *   DEMANDE_TRANSPORT  →  transport:request
 *   TRANSPORT_ORDER    →  transport:manage
 *
 * WHY IT WAS ONE PERMISSION, AND WHY THAT WAS WRONG. WES-4G.9 gated BOTH
 * artifacts on `transport:manage`, reasoning that "both artifacts describe the
 * transport leg and are produced by whoever plans it". But the two artifacts are
 * not one act. The platform's own source contract already separates them: a
 * Demande ends with `requestedBy` / `requestedAt` and needs no vehicle, while an
 * Ordre cannot exist without a driver and a plate (or, RQ-18, the carrier it was
 * confided to). Request precedes assignment; order presupposes it.
 *
 * So the Account Manager — who holds the permission literally named « Raise a
 * transport request » — could not produce the request, and could not upload one
 * either, because a generatable type refuses manual upload. On
 * EFT-IMP-2026-00013 that dead end is visible in the record: the AM filed a
 * hand-made « Demande_de_transport_….pdf » under the uploadable twin type
 * forty minutes after the generator refused them.
 *
 * NOTHING IS GRANTED HERE. Both permissions already exist and are already held
 * by the seats that need them (`transport:request` since the process-engine
 * seed, `transport:manage` since Phase 8.4). This map only stops asking the
 * wrong one of the two. The rule it states is a NARROWING for the Ordre — a
 * `transport:request` holder gains no power over it — and an opening for the
 * Demande, to exactly the seat whose job it names.
 */

/**
 * The permission `generateArtifact` asserts, per artifact code.
 *
 * Every ON_DEMAND artifact must appear here; an artifact absent from this map
 * cannot be generated by anyone, which is the safe direction for a code nobody
 * has decided the authority for yet.
 */
export const ARTIFACT_GENERATION_PERMISSION: Readonly<Record<string, string>> = {
  // The REQUEST act. Raised by the Account Manager at dossier preparation,
  // before any vehicle exists (registry step 3, `transport:request`).
  DEMANDE_TRANSPORT: "transport:request",
  // The EXECUTION act. Issued by the Transport function once it has planned the
  // mission — it names a driver and a vehicle, or the carrier it was given to.
  TRANSPORT_ORDER: "transport:manage",
};

/**
 * The permission required to generate this artifact, or null when the platform
 * does not let anyone generate it on demand.
 *
 * Null is a REFUSAL, never a pass: callers must treat it as "nobody may", which
 * is what keeps an unlisted code ungeneratable rather than ungoverned.
 */
export function artifactGenerationPermission(code: string): string | null {
  return ARTIFACT_GENERATION_PERMISSION[code] ?? null;
}
