"use server";

/**
 * Transactional tenant provisioning (Phase 6.0A). SERVER ACTION — platform only.
 * ---------------------------------------------------------------------------
 * The two-stage protocol the audit approved (commit 70dd907):
 *
 *   Stage 1 (GoTrue API)   create-or-reuse the administrator's auth.users row
 *   Stage 2 (ONE SQL txn)  provision_tenant() — all relational data, atomic
 *   Compensation           if stage 2 failed AND stage 1 CREATED the user, delete it
 *   Stage 3 (best effort)  send the secure setup invitation — never rolls anything back
 *
 * WHY THE STAGES CANNOT BE MERGED
 *
 * auth.users is GoTrue's, written through its API, not SQL — so the login cannot be
 * created inside the transaction that creates everything else. That single fact is
 * the whole reason this is a protocol and not one call, and it is why compensation
 * exists: the one thing outside the transaction has to be undone by hand when the
 * transaction fails.
 *
 * IDEMPOTENCY heals an orphan. If stage 1 created the auth user and stage 2 failed,
 * a retry with the same idempotencyKey: stage 1 REUSES that now-orphaned auth user
 * (does not create a second), stage 2 succeeds, the orphan becomes the admin. If
 * stage 2 had already succeeded, it returns already_exists and stage 1's reuse is a
 * no-op. Either way, at most one tenant per key.
 *
 * THE SECRET NEVER TOUCHES SQL OR THE LOG. The setup link is generated by GoTrue in
 * stage 3, handed to the caller ONCE for display, and dropped. It is never a
 * function argument to provision_tenant, never in an audit payload, never logged.
 */
import { getAdminSupabaseClient } from "@/lib/supabase/admin";
import { assertPlatformPermission, PlatformAuthError } from "@/lib/platform/auth";
import { validateProvisionInput } from "./validate";
import { selectTenantRoleTemplates } from "@/lib/platform/role-templates";
import { resolveTenantModules } from "@/lib/platform/entitlements";
import { staffWelcomeVars } from "@/lib/users/welcome";
import { queueAndSend } from "@/lib/comms/queue";
import { isProviderConfigured } from "@/lib/comms/provider";
import { reportError } from "@/lib/observability/report";
import type { ProvisionTenantInput, ProvisionTenantResult } from "./contract";
import type { ProvisionErrorCode } from "./errors";

/**
 * How the administrator was invited:
 *   "email_sent"    the secure setup email was queued (provider configured);
 *   "link_returned" no provider — the one-time setup link is here, show it ONCE;
 *   "failed"        neither worked (no link could even be generated).
 * The link is present ONLY in the "link_returned" case and is never persisted.
 */
export type InvitationOutcome =
  | { kind: "email_sent" }
  | { kind: "link_returned"; setupLink: string }
  | { kind: "failed"; reason: ProvisionErrorCode };

export type ProvisionOutcome =
  | { ok: true; result: ProvisionTenantResult; invitation: InvitationOutcome }
  | { ok: false; error: ProvisionErrorCode; detail?: string };

type SqlOk = {
  status: "provisioned" | "already_exists";
  organizationId: string;
  administratorUserId: string;
  createdRoles: string[];
  createdPermissionCount: number;
  enabledModules: unknown;
};
type SqlErr = { status: "error"; error: string };

export async function provisionTenant(input: ProvisionTenantInput): Promise<ProvisionOutcome> {
  // --- authorization --------------------------------------------------------
  let actor;
  try {
    actor = await assertPlatformPermission("platform:companies:create");
  } catch (e) {
    if (e instanceof PlatformAuthError) return { ok: false, error: "unauthorized" };
    throw e;
  }

  // --- validation (pure, reused from 4.0B) ----------------------------------
  const valid = validateProvisionInput(input);
  if (!valid.ok) return { ok: false, error: "invalid_input", detail: valid.errors.join("; ") };

  const admin = getAdminSupabaseClient();
  const adminEmail = input.administrator.email.trim().toLowerCase();

  // ==========================================================================
  // STAGE 1 — create or reuse the administrator's auth user.
  // ==========================================================================
  const { authId, createdHere, stage1Error } = await resolveOrCreateAuthUser(admin, adminEmail);
  if (stage1Error) return { ok: false, error: stage1Error };
  if (!authId) return { ok: false, error: "auth_user_creation_failed" };

  // The role catalog stays in TypeScript; we hand the SELECTED templates to SQL.
  const templates = selectTenantRoleTemplates(input.businessProfile);
  const roles = templates.map((t) => ({
    code: t.key,
    labelFr: t.labelFr,
    labelEn: t.labelEn,
    permissions: t.permissions,
  }));
  const enabledModules = resolveTenantModules(input.plan, input.modules);

  const lifecycleStatus = "TRIAL";
  const payload = {
    company: input.company,
    administrator: { fullName: input.administrator.fullName, email: adminEmail },
    lifecycleStatus,
    planKey: input.plan,
    trialEndsAt: null,
    idempotencyKey: input.idempotencyKey,
    enabledModules,
    roles,
  };

  // ==========================================================================
  // STAGE 2 — the atomic relational provision.
  // ==========================================================================
  const { data, error } = await admin.rpc("provision_tenant", {
    p_admin_auth_id: authId,
    p_platform_actor_id: actor.id,
    // payload is a plain JSON object; the generated RPC arg type is Json.
    p_input: payload as unknown as import("@/lib/db/types").Json,
  });

  if (error) {
    await compensate(admin, { authId, createdHere }, "rpc_error");
    return { ok: false, error: "relational_provisioning_failed", detail: error.message };
  }

  const res = data as unknown as SqlOk | SqlErr;

  if (res.status === "error") {
    // duplicate_slug / admin_email_conflict / invalid_input were refused BEFORE any
    // write, so there is nothing relational to roll back — but if THIS request created
    // the auth user for a slug that turned out to be taken, that user is now an orphan
    // we must remove.
    await compensate(admin, { authId, createdHere }, res.error);
    return { ok: false, error: mapSqlError(res.error) };
  }

  const provisioned = res.status === "provisioned";

  // ==========================================================================
  // STAGE 3 — invite the administrator. Best effort: the tenant already exists, so a
  // mail failure is a WARNING, never a rollback.
  // ==========================================================================
  const result: ProvisionTenantResult = {
    organizationId: res.organizationId,
    tenantId: res.organizationId,
    administratorUserId: res.administratorUserId,
    administratorLogin: adminEmail,
    createdRoles: res.createdRoles,
    createdDepartments: [], // no department entity exists; roles carry the structure
    enabledModules: enabledModules as string[],
    status: provisioned ? "provisioned" : "already_exists",
  };

  const invitation = await inviteAdministrator(admin, {
    tenantId: res.organizationId,
    actorId: res.administratorUserId,
    email: adminEmail,
    name: input.administrator.fullName,
  });

  return { ok: true, result, invitation };
}

// ---------------------------------------------------------------------------
// Stage 1
// ---------------------------------------------------------------------------
async function resolveOrCreateAuthUser(
  admin: ReturnType<typeof getAdminSupabaseClient>,
  email: string,
): Promise<{ authId: string | null; createdHere: boolean; stage1Error?: ProvisionErrorCode }> {
  // Reuse first. An existing auth user (a prior signup, or an orphan from a failed
  // provision) is reused — never re-created. Paged lookup by email.
  const existing = await findAuthUserByEmail(admin, email);
  if (existing) return { authId: existing, createdHere: false };

  const { data, error } = await admin.auth.admin.createUser({
    email,
    email_confirm: true, // they set their own password via the recovery link; no temp password
  });
  if (error || !data.user) {
    reportError(error, { scope: "action", event: "provision.auth_create" });
    return { authId: null, createdHere: false, stage1Error: "auth_user_creation_failed" };
  }
  return { authId: data.user.id, createdHere: true };
}

async function findAuthUserByEmail(
  admin: ReturnType<typeof getAdminSupabaseClient>,
  email: string,
): Promise<string | null> {
  // GoTrue's admin API has no direct get-by-email; page until found or exhausted.
  for (let page = 1; page <= 20; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) {
      reportError(error, { scope: "action", event: "provision.auth_lookup" });
      return null;
    }
    const hit = data.users.find((u) => (u.email ?? "").toLowerCase() === email);
    if (hit) return hit.id;
    if (data.users.length < 200) break; // last page
  }
  return null;
}

// ---------------------------------------------------------------------------
// Compensation — delete the auth user ONLY if this request created it.
// ---------------------------------------------------------------------------
async function compensate(
  admin: ReturnType<typeof getAdminSupabaseClient>,
  ctx: { authId: string; createdHere: boolean },
  reason: string,
): Promise<void> {
  // A pre-existing auth user is NEVER deleted — they may be a real person with a real
  // login who simply is not yet a tenant admin. We only undo what we did.
  if (!ctx.createdHere) return;
  const { error } = await admin.auth.admin.deleteUser(ctx.authId);
  if (error) {
    // Honest reporting: a failed compensation leaves an orphan auth user. That is
    // recoverable — the next retry with the same idempotencyKey reuses this exact user
    // — but it must be visible, not swallowed.
    reportError(error, {
      scope: "action",
      event: "provision.compensation_failed",
      extra: { authId: ctx.authId, reason },
    });
  }
}

// ---------------------------------------------------------------------------
// Stage 3 — invitation. Never claims an email was sent when it was not.
// ---------------------------------------------------------------------------
async function inviteAdministrator(
  admin: ReturnType<typeof getAdminSupabaseClient>,
  who: { tenantId: string; actorId: string; email: string; name: string },
): Promise<InvitationOutcome> {
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "";
  const loginUrl = `${siteUrl}/login`;

  // The secure setup link (GoTrue recovery link). Generated here, shown once, never
  // stored. The administrator sets their own password — no permanent password is ever
  // emailed (the house rule since Phase 1.19).
  const { data: link } = await admin.auth.admin.generateLink({
    type: "recovery",
    email: who.email,
    options: { redirectTo: `${siteUrl}/auth/update-password` },
  });
  const setupLink = link?.properties?.action_link ?? null;

  // No provider configured => we must NOT pretend to have emailed anything. Hand the
  // link back to the platform admin to deliver out of band.
  if (!isProviderConfigured()) {
    return setupLink
      ? { kind: "link_returned", setupLink }
      : { kind: "failed", reason: "invitation_send_failed" };
  }

  try {
    const res = await queueAndSend({
      tenantId: who.tenantId,
      createdBy: who.actorId,
      templateKey: "staff_welcome",
      vars: staffWelcomeVars({
        name: who.name,
        email: who.email,
        loginUrl,
        setupLink: setupLink ?? loginUrl,
      }),
      recipientEmail: who.email,
      recipientName: who.name,
      related: "user",
      relatedId: who.actorId,
    });
    return res.id ? { kind: "email_sent" } : { kind: "failed", reason: "invitation_send_failed" };
  } catch (e) {
    reportError(e, { scope: "action", event: "provision.invitation" });
    return { kind: "failed", reason: "invitation_send_failed" };
  }
}

function mapSqlError(code: string): ProvisionErrorCode {
  switch (code) {
    case "duplicate_slug":
      return "duplicate_slug";
    case "admin_email_conflict":
      return "admin_email_conflict";
    case "invalid_input":
      return "invalid_input";
    case "auth_user_creation_failed":
      return "auth_user_creation_failed";
    default:
      return "relational_provisioning_failed";
  }
}
